# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.logging import LogConfig, Logger
from .environment import StarterEnvironment
from .wkmath import AsyncStarter as wkmath_AsyncStarter
from .wkmath import Starter as wkmath_Starter


class Starter(wkmath_Starter):
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: StarterEnvironment = StarterEnvironment.LOCAL,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            environment=environment,
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )


class AsyncStarter(wkmath_AsyncStarter):
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: StarterEnvironment = StarterEnvironment.LOCAL,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            environment=environment,
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )
