# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.request_options import RequestOptions
from .raw_wkmath import AsyncRawStarter, RawStarter
from .types.add_response import AddResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class Starter:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from wkmath import Starter

    client = Starter(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = RawStarter(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawStarter:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStarter
        """
        return self._raw_client

    def add(self, *, a: float, b: float, request_options: typing.Optional[RequestOptions] = None) -> AddResponse:
        """
        Calculates the sum of two numbers provided in the request body.

        Parameters
        ----------
        a : float
            The first number to add.

        b : float
            The second number to add.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddResponse
            Successful Response

        Examples
        --------
        from wkmath import Starter

        client = Starter(
            base_url="https://yourhost.com/path/to/api",
        )
        client.add(
            a=1.1,
            b=1.1,
        )
        """
        _response = self._raw_client.add(a=a, b=b, request_options=request_options)
        return _response.data


class AsyncStarter:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from wkmath import AsyncStarter

    client = AsyncStarter(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = AsyncRawStarter(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStarter:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStarter
        """
        return self._raw_client

    async def add(self, *, a: float, b: float, request_options: typing.Optional[RequestOptions] = None) -> AddResponse:
        """
        Calculates the sum of two numbers provided in the request body.

        Parameters
        ----------
        a : float
            The first number to add.

        b : float
            The second number to add.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddResponse
            Successful Response

        Examples
        --------
        import asyncio

        from wkmath import AsyncStarter

        client = AsyncStarter(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.add(
                a=1.1,
                b=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(a=a, b=b, request_options=request_options)
        return _response.data
